# action.yml
name: "Post Workflow Status To Slack"
description: "Post workflows Success/Failure/Cancel job status to Slack using bot"
author: "Pritam Kadam"

inputs:
  job-status:
    description: "Job status i.e. Success/Failure/Cancelled"
    required: true
  slack-bot-token:
    description: "Slack bot token used to send message to slack channel"
    required: true
  channel:
    description: "Slack channel where job status message will be posted"
    required: true
  extra-args:
    description: "Comma separated extra arguments passed to slack post API as it, refer https://api.slack.com/methods/chat.postMessage"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.job-status }}
    - ${{ inputs.slack-bot-token }}
    - ${{ inputs.channel }}
    - ${{ inputs.extra-args }}

branding:
  icon: "activity"
  color: "green"
